//! Code generated by internal/zigui/wiregen. DO NOT EDIT.
//! RZW1 state-wire decoders (the binary v2 path). Strings are slices INTO the input
//! buffer (zero-copy); lists come from the parse arena. Unknown field numbers are
//! skipped, so a newer Go encoder stays readable; a schema-hash mismatch is rejected
//! by wire.parse before any field is read.

const std = @import("std");
const wire = @import("wire.zig");
const appgroups = @import("appgroups.zig");
const logs = @import("logs.zig");
const c = @import("components.zig");

pub const schema_hash: u32 = 0xfe16917d;
pub const msg_ag_state: u16 = 1; // App Groups tab (full view + the #appgroups-body fragment share this state)
pub const msg_logs_state: u16 = 2; // Logs tab (full view)
pub const msg_logs_lines: u16 = 3; // #log-view inner fragment (filter change + ~1 Hz tick)

pub fn decodeAgApp(r: *wire.Reader, out: *appgroups.App) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.base = try r.str(t),
        2 => out.elevated = try r.boolean(t),
        else => try r.skip(t),
    };
}

pub fn decodeAgGroup(r: *wire.Reader, out: *appgroups.Group) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.id = try r.str(t),
        2 => out.name = try r.str(t),
        3 => out.up = try r.str(t),
        4 => out.variant = try r.str(t),
        5 => out.apps = try r.list(appgroups.App, decodeAgApp, t),
        else => try r.skip(t),
    };
}

pub fn decodeAgState(r: *wire.Reader, out: *appgroups.State) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.title = try r.str(t),
        2 => out.subtitle = try r.str(t),
        3 => out.available = try r.boolean(t),
        4 => out.unavailable = try r.str(t),
        5 => out.empty = try r.str(t),
        6 => out.admin = try r.str(t),
        7 => out.launch = try r.str(t),
        8 => out.groups = try r.list(appgroups.Group, decodeAgGroup, t),
        else => try r.skip(t),
    };
}

pub fn decodeSelRow(r: *wire.Reader, out: *c.SelectRow) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.val = try r.str(t),
        2 => out.label = try r.str(t),
        3 => out.sub = try r.str(t),
        4 => out.badge = try r.str(t),
        5 => out.cur = try r.boolean(t),
        else => try r.skip(t),
    };
}

pub fn decodeSelState(r: *wire.Reader, out: *c.Select) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.id = try r.str(t),
        2 => out.label = try r.str(t),
        3 => out.curLabel = try r.str(t),
        4 => out.open = try r.boolean(t),
        5 => out.filter = try r.str(t),
        6 => out.rows = try r.list(c.SelectRow, decodeSelRow, t),
        else => try r.skip(t),
    };
}

pub fn decodeLogsTab(r: *wire.Reader, out: *c.Tab) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.val = try r.str(t),
        2 => out.label = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLogsEntry(r: *wire.Reader, out: *logs.Entry) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.time = try r.str(t),
        2 => out.lvl = try r.str(t),
        3 => out.cls = try r.str(t),
        4 => out.src = try r.str(t),
        5 => out.msg = try r.str(t),
        6 => out.fields = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLogsLines(r: *wire.Reader, out: *logs.Lines) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.wired = try r.boolean(t),
        2 => out.noBus = try r.str(t),
        3 => out.noEntries = try r.str(t),
        4 => out.entries = try r.list(logs.Entry, decodeLogsEntry, t),
        else => try r.skip(t),
    };
}

pub fn decodeLogsState(r: *wire.Reader, out: *logs.State) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.title = try r.str(t),
        2 => out.sub = try r.str(t),
        3 => out.showBus = try r.boolean(t),
        4 => out.busActive = try r.str(t),
        5 => out.busItems = try r.list(c.Tab, decodeLogsTab, t),
        6 => out.level = try r.sub(c.Select, decodeSelState, t),
        7 => out.source = try r.sub(c.Select, decodeSelState, t),
        8 => out.searchLabel = try r.str(t),
        9 => out.searchPh = try r.str(t),
        10 => out.searchVal = try r.str(t),
        11 => out.autoLabel = try r.str(t),
        12 => out.autoDl = try r.str(t),
        13 => out.autoOn = try r.boolean(t),
        14 => out.copy = try r.str(t),
        15 => out.clear = try r.str(t),
        16 => out.tailing = try r.str(t),
        17 => out.lines = try r.sub(logs.Lines, decodeLogsLines, t),
        else => try r.skip(t),
    };
}

test "schema ids are distinct" {
    try std.testing.expect(msg_ag_state != msg_logs_state);
    try std.testing.expect(msg_ag_state != msg_logs_lines);
    try std.testing.expect(msg_logs_state != msg_logs_lines);
}
