//! Code generated by internal/zigui/wiregen. DO NOT EDIT.
//! RZW1 state-wire decoders (the binary v2 path). Strings are slices INTO the input
//! buffer (zero-copy); lists come from the parse arena. Unknown field numbers are
//! skipped, so a newer Go encoder stays readable; a schema-hash mismatch is rejected
//! by wire.parse before any field is read.

const std = @import("std");
const wire = @import("wire.zig");
const appgroups = @import("appgroups.zig");
const logs = @import("logs.zig");
const c = @import("components.zig");
const sub = @import("settings_sub.zig");
const settings = @import("settings.zig");
const publish = @import("publish.zig");
const motion = @import("motion.zig");
const live = @import("live.zig");

pub const schema_hash: u32 = 0xf842f2ca;
pub const msg_ag_state: u16 = 1; // App Groups tab (full view + the #appgroups-body fragment share this state)
pub const msg_logs_state: u16 = 2; // Logs tab (full view)
pub const msg_logs_lines: u16 = 3; // #log-view inner fragment (filter change + ~1 Hz tick)
pub const msg_live_state: u16 = 10; // Live tab - full cockpit
pub const msg_live_transport: u16 = 11; // #live-transport fragment
pub const msg_live_n_p: u16 = 12; // #live-np fragment
pub const msg_live_status: u16 = 13; // #live-status fragment
pub const msg_live_decks: u16 = 14; // #live-decks fragment
pub const msg_live_signals: u16 = 15; // #live-signals fragment
pub const msg_live_cockpit: u16 = 16; // #live-cockpit fragment
pub const msg_live_link: u16 = 17; // #live-ablelink fragment
pub const msg_live_graph: u16 = 18; // #live-net + #live-tim fragments
pub const msg_live_perf: u16 = 19; // #live-perf2 fragment
pub const msg_live_strip: u16 = 20; // #live-strip fragment
pub const msg_mo_state: u16 = 21; // Motion tab (full view + the #mo-body fragment share this state)
pub const msg_pub: u16 = 22; // Publish tab (full view)
pub const msg_pub_hero: u16 = 23; // #pub-hero fragment (~1 Hz tick)
pub const msg_set_state: u16 = 24; // Settings tab (full view)
pub const msg_set_content: u16 = 25; // #set-content pane (sub-tab switch + search)
pub const msg_set_status: u16 = 26; // one #stset-<id> status fragment (settings tick)

pub fn decodeAgApp(r: *wire.Reader, out: *appgroups.App) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.base = try r.str(t),
        2 => out.elevated = try r.boolean(t),
        else => try r.skip(t),
    };
}

pub fn decodeAgGroup(r: *wire.Reader, out: *appgroups.Group) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.id = try r.str(t),
        2 => out.name = try r.str(t),
        3 => out.up = try r.str(t),
        4 => out.variant = try r.str(t),
        5 => out.apps = try r.list(appgroups.App, decodeAgApp, t),
        else => try r.skip(t),
    };
}

pub fn decodeAgState(r: *wire.Reader, out: *appgroups.State) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.title = try r.str(t),
        2 => out.subtitle = try r.str(t),
        3 => out.available = try r.boolean(t),
        4 => out.unavailable = try r.str(t),
        5 => out.empty = try r.str(t),
        6 => out.admin = try r.str(t),
        7 => out.launch = try r.str(t),
        8 => out.groups = try r.list(appgroups.Group, decodeAgGroup, t),
        else => try r.skip(t),
    };
}

pub fn decodeSelRow(r: *wire.Reader, out: *c.SelectRow) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.val = try r.str(t),
        2 => out.label = try r.str(t),
        3 => out.sub = try r.str(t),
        4 => out.badge = try r.str(t),
        5 => out.cur = try r.boolean(t),
        else => try r.skip(t),
    };
}

pub fn decodeSelState(r: *wire.Reader, out: *c.Select) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.id = try r.str(t),
        2 => out.label = try r.str(t),
        3 => out.curLabel = try r.str(t),
        4 => out.open = try r.boolean(t),
        5 => out.filter = try r.str(t),
        6 => out.rows = try r.list(c.SelectRow, decodeSelRow, t),
        else => try r.skip(t),
    };
}

pub fn decodeLogsTab(r: *wire.Reader, out: *c.Tab) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.val = try r.str(t),
        2 => out.label = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLogsEntry(r: *wire.Reader, out: *logs.Entry) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.time = try r.str(t),
        2 => out.lvl = try r.str(t),
        3 => out.cls = try r.str(t),
        4 => out.src = try r.str(t),
        5 => out.msg = try r.str(t),
        6 => out.fields = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLogsLines(r: *wire.Reader, out: *logs.Lines) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.wired = try r.boolean(t),
        2 => out.noBus = try r.str(t),
        3 => out.noEntries = try r.str(t),
        4 => out.entries = try r.list(logs.Entry, decodeLogsEntry, t),
        else => try r.skip(t),
    };
}

pub fn decodeLogsState(r: *wire.Reader, out: *logs.State) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.title = try r.str(t),
        2 => out.sub = try r.str(t),
        3 => out.showBus = try r.boolean(t),
        4 => out.busActive = try r.str(t),
        5 => out.busItems = try r.list(c.Tab, decodeLogsTab, t),
        6 => out.level = try r.sub(c.Select, decodeSelState, t),
        7 => out.source = try r.sub(c.Select, decodeSelState, t),
        8 => out.searchLabel = try r.str(t),
        9 => out.searchPh = try r.str(t),
        10 => out.searchVal = try r.str(t),
        11 => out.autoLabel = try r.str(t),
        12 => out.autoDl = try r.str(t),
        13 => out.autoOn = try r.boolean(t),
        14 => out.copy = try r.str(t),
        15 => out.clear = try r.str(t),
        16 => out.tailing = try r.str(t),
        17 => out.lines = try r.sub(logs.Lines, decodeLogsLines, t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveTransport(r: *wire.Reader, out: *live.Transport) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.streamHint = try r.str(t),
        2 => out.streamLabel = try r.str(t),
        3 => out.dotVar = try r.str(t),
        4 => out.state = try r.str(t),
        5 => out.metaOnly = try r.str(t),
        6 => out.pauseLabel = try r.str(t),
        7 => out.pauseHint = try r.str(t),
        8 => out.paused = try r.boolean(t),
        9 => out.hasRec = try r.boolean(t),
        10 => out.recHint = try r.str(t),
        11 => out.recLabel = try r.str(t),
        12 => out.recBtn = try r.str(t),
        13 => out.recState = try r.str(t),
        14 => out.hasTc = try r.boolean(t),
        15 => out.tcLabel = try r.str(t),
        16 => out.tc = try r.str(t),
        17 => out.startLbl = try r.str(t),
        18 => out.stopLbl = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveNP(r: *wire.Reader, out: *live.NP) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.line1 = try r.str(t),
        2 => out.line2 = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveKV(r: *wire.Reader, out: *live.KV) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.k = try r.str(t),
        2 => out.kl = try r.str(t),
        3 => out.v = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveStatus(r: *wire.Reader, out: *live.Status) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.rows = try r.list(live.KV, decodeLiveKV, t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveDeck(r: *wire.Reader, out: *live.Deck) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.cls = try r.str(t),
        2 => out.name = try r.str(t),
        3 => out.title = try r.str(t),
        4 => out.meta = try r.str(t),
        5 => out.via = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveDecks(r: *wire.Reader, out: *live.Decks) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.note = try r.str(t),
        2 => out.decks = try r.list(live.Deck, decodeLiveDeck, t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveSignals(r: *wire.Reader, out: *live.Signals) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.rows = try r.list(live.KV, decodeLiveKV, t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveCockpitRow(r: *wire.Reader, out: *live.CockpitRow) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.variant = try r.str(t),
        2 => out.name = try r.str(t),
        3 => out.state = try r.str(t),
        4 => out.streamLbl = try r.str(t),
        5 => out.streamAct = try r.str(t),
        6 => out.recLbl = try r.str(t),
        7 => out.recAct = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveCockpit(r: *wire.Reader, out: *live.Cockpit) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.empty = try r.str(t),
        2 => out.caption = try r.str(t),
        3 => out.rows = try r.list(live.CockpitRow, decodeLiveCockpitRow, t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveSRow(r: *wire.Reader, out: *live.SRow) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.variant = try r.str(t),
        2 => out.label = try r.str(t),
        3 => out.dl = try r.str(t),
        4 => out.line = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveLink(r: *wire.Reader, out: *live.Link) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.available = try r.boolean(t),
        2 => out.backend = try r.sub(live.SRow, decodeLiveSRow, t),
        3 => out.fill = try r.str(t),
        4 => out.cap = try r.str(t),
        5 => out.session = try r.sub(live.SRow, decodeLiveSRow, t),
        6 => out.resyncLbl = try r.str(t),
        7 => out.sources = try r.list(live.SRow, decodeLiveSRow, t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveGraph(r: *wire.Reader, out: *live.Graph) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.tooltip = try r.str(t),
        2 => out.legend = try r.str(t),
        3 => out.graph = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLivePerf(r: *wire.Reader, out: *live.Perf) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.tooltip = try r.str(t),
        2 => out.cpuLeg = try r.str(t),
        3 => out.cpuGraph = try r.str(t),
        4 => out.ramLeg = try r.str(t),
        5 => out.ramGraph = try r.str(t),
        6 => out.head = try r.str(t),
        7 => out.headColor = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveStrip(r: *wire.Reader, out: *live.Strip) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.left = try r.str(t),
        2 => out.center = try r.str(t),
        3 => out.right = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeLiveState(r: *wire.Reader, out: *live.State) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.title = try r.str(t),
        2 => out.sub = try r.str(t),
        3 => out.transport = try r.sub(live.Transport, decodeLiveTransport, t),
        4 => out.np = try r.sub(live.NP, decodeLiveNP, t),
        5 => out.statusTitle = try r.str(t),
        6 => out.status = try r.sub(live.Status, decodeLiveStatus, t),
        7 => out.decksTitle = try r.str(t),
        8 => out.decks = try r.sub(live.Decks, decodeLiveDecks, t),
        9 => out.hasSignals = try r.boolean(t),
        10 => out.signalsTitle = try r.str(t),
        11 => out.signalsTip = try r.str(t),
        12 => out.signals = try r.sub(live.Signals, decodeLiveSignals, t),
        13 => out.hasCockpit = try r.boolean(t),
        14 => out.cockpitTitle = try r.str(t),
        15 => out.cockpit = try r.sub(live.Cockpit, decodeLiveCockpit, t),
        16 => out.hasLink = try r.boolean(t),
        17 => out.linkTitle = try r.str(t),
        18 => out.link = try r.sub(live.Link, decodeLiveLink, t),
        19 => out.hasNet = try r.boolean(t),
        20 => out.netTitle = try r.str(t),
        21 => out.netTip = try r.str(t),
        22 => out.net = try r.sub(live.Graph, decodeLiveGraph, t),
        23 => out.timTitle = try r.str(t),
        24 => out.timTip = try r.str(t),
        25 => out.tim = try r.sub(live.Graph, decodeLiveGraph, t),
        26 => out.hasPerf = try r.boolean(t),
        27 => out.perfTitle = try r.str(t),
        28 => out.perfTip = try r.str(t),
        29 => out.perf = try r.sub(live.Perf, decodeLivePerf, t),
        30 => out.strip = try r.sub(live.Strip, decodeLiveStrip, t),
        else => try r.skip(t),
    };
}

pub fn decodeMoCamRow(r: *wire.Reader, out: *motion.CamRow) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.group = try r.str(t),
        2 => out.showGroup = try r.boolean(t),
        3 => out.act = try r.str(t),
        4 => out.sel = try r.boolean(t),
        5 => out.name = try r.str(t),
        6 => out.meta = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeMoCam(r: *wire.Reader, out: *motion.Cam) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.unavailable = try r.str(t),
        2 => out.rows = try r.list(motion.CamRow, decodeMoCamRow, t),
        3 => out.empty = try r.str(t),
        4 => out.reloadLbl = try r.str(t),
        5 => out.organizeLbl = try r.str(t),
        6 => out.djLbl = try r.str(t),
        7 => out.previewLbl = try r.str(t),
        8 => out.tip = try r.str(t),
        9 => out.view = try r.str(t),
        10 => out.hint = try r.str(t),
        11 => out.info = try r.str(t),
        12 => out.playBtn = try r.str(t),
        13 => out.loadLbl = try r.str(t),
        14 => out.copyLbl = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeMoRecRow(r: *wire.Reader, out: *motion.RecRow) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.name = try r.str(t),
        2 => out.act = try r.str(t),
        3 => out.sel = try r.boolean(t),
        else => try r.skip(t),
    };
}

pub fn decodeMoAvatar(r: *wire.Reader, out: *motion.Avatar) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.label = try r.str(t),
        2 => out.sel = try r.sub(c.Select, decodeSelState, t),
        3 => out.importLbl = try r.str(t),
        4 => out.syncLbl = try r.str(t),
        5 => out.info = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeMoSlider(r: *wire.Reader, out: *c.Slider) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.label = try r.str(t),
        2 => out.dl = try r.str(t),
        3 => out.act = try r.str(t),
        4 => out.unit = try r.str(t),
        5 => out.unitJs = try r.str(t),
        6 => out.minS = try r.str(t),
        7 => out.maxS = try r.str(t),
        8 => out.stepS = try r.str(t),
        9 => out.valS = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeMoToggle(r: *wire.Reader, out: *motion.Toggle) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.label = try r.str(t),
        2 => out.dl = try r.str(t),
        3 => out.act = try r.str(t),
        4 => out.on = try r.boolean(t),
        else => try r.skip(t),
    };
}

pub fn decodeMoStudio(r: *wire.Reader, out: *motion.Studio) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.recs = try r.list(motion.RecRow, decodeMoRecRow, t),
        2 => out.empty = try r.str(t),
        3 => out.refreshLbl = try r.str(t),
        4 => out.exportLbl = try r.str(t),
        5 => out.renderLbl = try r.str(t),
        6 => out.pcViewLbl = try r.str(t),
        7 => out.renderProg = try r.str(t),
        8 => out.avatar = try r.sub(motion.Avatar, decodeMoAvatar, t),
        9 => out.previewLbl = try r.str(t),
        10 => out.tip = try r.str(t),
        11 => out.view = try r.str(t),
        12 => out.hint = try r.str(t),
        13 => out.time = try r.str(t),
        14 => out.scrub = try r.sub(c.Slider, decodeMoSlider, t),
        15 => out.playLbl = try r.str(t),
        16 => out.stopLbl = try r.str(t),
        17 => out.loop = try r.sub(motion.Toggle, decodeMoToggle, t),
        18 => out.osc = try r.sub(motion.Toggle, decodeMoToggle, t),
        19 => out.vmc = try r.sub(motion.Toggle, decodeMoToggle, t),
        20 => out.model = try r.sub(motion.Toggle, decodeMoToggle, t),
        21 => out.modelOn = try r.boolean(t),
        22 => out.hasDyn = try r.boolean(t),
        23 => out.physNote = try r.str(t),
        24 => out.phys = try r.sub(motion.Toggle, decodeMoToggle, t),
        25 => out.rest = try r.sub(motion.Toggle, decodeMoToggle, t),
        26 => out.marks = try r.sub(motion.Toggle, decodeMoToggle, t),
        27 => out.pc = try r.sub(motion.Toggle, decodeMoToggle, t),
        28 => out.pcOn = try r.boolean(t),
        29 => out.pcDensity = try r.sub(c.Select, decodeSelState, t),
        30 => out.pcColor = try r.sub(motion.Toggle, decodeMoToggle, t),
        31 => out.pcNote = try r.str(t),
        32 => out.pcExportLbl = try r.str(t),
        33 => out.vmcHelp = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeMoState(r: *wire.Reader, out: *motion.State) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.title = try r.str(t),
        2 => out.sub = try r.str(t),
        3 => out.section = try r.str(t),
        4 => out.tabCam = try r.str(t),
        5 => out.tabStudio = try r.str(t),
        6 => out.cam = try r.sub(motion.Cam, decodeMoCam, t),
        7 => out.studio = try r.sub(motion.Studio, decodeMoStudio, t),
        else => try r.skip(t),
    };
}

pub fn decodePubBadge(r: *wire.Reader, out: *publish.Badge) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.key = try r.str(t),
        2 => out.dl = try r.str(t),
        3 => out.variant = try r.str(t),
        4 => out.line = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodePubBar(r: *wire.Reader, out: *publish.Bar) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.show = try r.boolean(t),
        2 => out.pct = try r.str(t),
        3 => out.cap = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodePubNp(r: *wire.Reader, out: *publish.Np) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.label = try r.str(t),
        2 => out.title = try r.str(t),
        3 => out.meta = try r.str(t),
        4 => out.state = try r.str(t),
        5 => out.bar = try r.sub(publish.Bar, decodePubBar, t),
        else => try r.skip(t),
    };
}

pub fn decodePubPlayer(r: *wire.Reader, out: *publish.Player) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.show = try r.boolean(t),
        2 => out.label = try r.str(t),
        3 => out.pos = try r.str(t),
        4 => out.bar = try r.sub(publish.Bar, decodePubBar, t),
        else => try r.skip(t),
    };
}

pub fn decodePubHero(r: *wire.Reader, out: *publish.Hero) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.show = try r.boolean(t),
        2 => out.rec = try r.sub(publish.Badge, decodePubBadge, t),
        3 => out.cap = try r.sub(publish.Badge, decodePubBadge, t),
        4 => out.obs = try r.sub(publish.Badge, decodePubBadge, t),
        5 => out.finish = try r.str(t),
        6 => out.np = try r.sub(publish.Np, decodePubNp, t),
        7 => out.player = try r.sub(publish.Player, decodePubPlayer, t),
        else => try r.skip(t),
    };
}

pub fn decodePubSetRow(r: *wire.Reader, out: *publish.SetRow) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.id = try r.str(t),
        2 => out.title = try r.str(t),
        3 => out.sub = try r.str(t),
        4 => out.sel = try r.boolean(t),
        5 => out.rename = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodePubList(r: *wire.Reader, out: *publish.List) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.empty = try r.str(t),
        2 => out.count = try r.str(t),
        3 => out.rows = try r.list(publish.SetRow, decodePubSetRow, t),
        else => try r.skip(t),
    };
}

pub fn decodeUiBtn(r: *wire.Reader, out: *c.Btn) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.label = try r.str(t),
        2 => out.variant = try r.str(t),
        3 => out.act = try r.str(t),
        4 => out.val = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodePubCap(r: *wire.Reader, out: *publish.Cap) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.caption = try r.str(t),
        2 => out.btns = try r.list(c.Btn, decodeUiBtn, t),
        3 => out.menu = try r.sub(c.Select, decodeSelState, t),
        else => try r.skip(t),
    };
}

pub fn decodePubLoose(r: *wire.Reader, out: *publish.Loose) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.count = try r.str(t),
        2 => out.desc = try r.str(t),
        3 => out.caps = try r.list(publish.Cap, decodePubCap, t),
        else => try r.skip(t),
    };
}

pub fn decodePubCaptures(r: *wire.Reader, out: *publish.Captures) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.player = try r.str(t),
        2 => out.empty = try r.str(t),
        3 => out.caps = try r.list(publish.Cap, decodePubCap, t),
        else => try r.skip(t),
    };
}

pub fn decodePubTrack(r: *wire.Reader, out: *publish.Track) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.num = @intCast(try r.uint(t)),
        2 => out.label = try r.str(t),
        3 => out.off = try r.str(t),
        4 => out.lead = try r.str(t),
        5 => out.leadTip = try r.str(t),
        6 => out.checked = try r.boolean(t),
        7 => out.path = try r.str(t),
        8 => out.ctx = try r.str(t),
        9 => out.offAct = try r.str(t),
        10 => out.offDl = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodePubBatch(r: *wire.Reader, out: *publish.Batch) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.count = try r.str(t),
        2 => out.btns = try r.list(c.Btn, decodeUiBtn, t),
        else => try r.skip(t),
    };
}

pub fn decodePubTracklist(r: *wire.Reader, out: *publish.Tracklist) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.empty = try r.str(t),
        2 => out.resolving = try r.str(t),
        3 => out.editable = try r.boolean(t),
        4 => out.offTip = try r.str(t),
        5 => out.rows = try r.list(publish.Track, decodePubTrack, t),
        6 => out.showFix = try r.boolean(t),
        7 => out.fix = try r.sub(c.Btn, decodeUiBtn, t),
        8 => out.help = try r.str(t),
        9 => out.unres = try r.str(t),
        10 => out.batch = try r.sub(publish.Batch, decodePubBatch, t),
        else => try r.skip(t),
    };
}

pub fn decodePubDetail(r: *wire.Reader, out: *publish.Detail) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.cardTitle = try r.str(t),
        2 => out.sel = try r.boolean(t),
        3 => out.hint = try r.str(t),
        4 => out.player = try r.str(t),
        5 => out.loose = try r.sub(publish.Loose, decodePubLoose, t),
        6 => out.name = try r.str(t),
        7 => out.meta = try r.str(t),
        8 => out.actions = try r.list(c.Btn, decodeUiBtn, t),
        9 => out.active = try r.str(t),
        10 => out.capsLbl = try r.str(t),
        11 => out.tracksLbl = try r.str(t),
        12 => out.captures = try r.sub(publish.Captures, decodePubCaptures, t),
        13 => out.tracklist = try r.sub(publish.Tracklist, decodePubTracklist, t),
        else => try r.skip(t),
    };
}

pub fn decodePubBody(r: *wire.Reader, out: *publish.Body) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.hero = try r.sub(publish.Hero, decodePubHero, t),
        2 => out.list = try r.sub(publish.List, decodePubList, t),
        3 => out.detail = try r.sub(publish.Detail, decodePubDetail, t),
        else => try r.skip(t),
    };
}

pub fn decodePub(r: *wire.Reader, out: *publish.State) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.title = try r.str(t),
        2 => out.sub = try r.str(t),
        3 => out.switcher = try r.str(t),
        4 => out.available = try r.boolean(t),
        5 => out.unavailable = try r.str(t),
        6 => out.body = try r.sub(publish.Body, decodePubBody, t),
        else => try r.skip(t),
    };
}

pub fn decodeSetNav(r: *wire.Reader, out: *settings.Nav) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.id = try r.str(t),
        2 => out.title = try r.str(t),
        3 => out.agg = try r.str(t),
        4 => out.active = try r.boolean(t),
        else => try r.skip(t),
    };
}

pub fn decodeTipChip(r: *wire.Reader, out: *c.TipChip) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.text = try r.str(t),
        2 => out.sep = try r.boolean(t),
        else => try r.skip(t),
    };
}

pub fn decodeTipKb(r: *wire.Reader, out: *c.TipKb) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.hasGroup = try r.boolean(t),
        2 => out.group = try r.str(t),
        3 => out.chips = try r.list(c.TipChip, decodeTipChip, t),
        4 => out.verb = try r.str(t),
        5 => out.rest = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeTipLink(r: *wire.Reader, out: *c.TipLink) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.label = try r.str(t),
        2 => out.url = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeTip(r: *wire.Reader, out: *c.Tip) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.id = try r.str(t),
        2 => out.title = try r.str(t),
        3 => out.keys = try r.list(c.TipKb, decodeTipKb, t),
        4 => out.paras = try r.strList(t),
        5 => out.links = try r.list(c.TipLink, decodeTipLink, t),
        else => try r.skip(t),
    };
}

pub fn decodeSetStatus(r: *wire.Reader, out: *settings.Status) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.v = try r.str(t),
        2 => out.t = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeSetSwitch(r: *wire.Reader, out: *settings.Switch) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.label = try r.str(t),
        2 => out.on = try r.boolean(t),
        3 => out.gate = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeUiField(r: *wire.Reader, out: *c.Field) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.label = try r.str(t),
        2 => out.dl = try r.str(t),
        3 => out.act = try r.str(t),
        4 => out.value = try r.str(t),
        5 => out.inputType = try r.str(t),
        6 => out.ph = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeUiToggle(r: *wire.Reader, out: *c.Toggle) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.label = try r.str(t),
        2 => out.dl = try r.str(t),
        3 => out.act = try r.str(t),
        4 => out.on = try r.boolean(t),
        else => try r.skip(t),
    };
}

pub fn decodeUiKV(r: *wire.Reader, out: *c.KV) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.label = try r.str(t),
        2 => out.dl = try r.str(t),
        3 => out.value = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeSetKid(r: *wire.Reader, out: *settings.Kid) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.k = try r.str(t),
        2 => out.fld = try r.sub(c.Field, decodeUiField, t),
        3 => out.tip = try r.str(t),
        4 => out.tipSt = try r.sub(c.Tip, decodeTip, t),
        5 => out.sel = try r.sub(c.Select, decodeSelState, t),
        6 => out.selLbl = try r.str(t),
        7 => out.btn = try r.sub(c.Btn, decodeUiBtn, t),
        else => try r.skip(t),
    };
}

pub fn decodeSetInput(r: *wire.Reader, out: *settings.Input) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.type = try r.str(t),
        2 => out.name = try r.str(t),
        3 => out.ph = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeGfBtn(r: *wire.Reader, out: *sub.GfBtn) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.label = try r.str(t),
        2 => out.variant = try r.str(t),
        3 => out.act = try r.str(t),
        4 => out.gate = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeGfVar(r: *wire.Reader, out: *sub.GfVar) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.key = try r.str(t),
        2 => out.tone = try r.str(t),
        3 => out.line = try r.str(t),
        4 => out.btns = try r.list(sub.GfBtn, decodeGfBtn, t),
        5 => out.hasNote = try r.boolean(t),
        6 => out.note = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeGfCard(r: *wire.Reader, out: *sub.GfCard) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.leadKind = try r.str(t),
        2 => out.leadTone = try r.str(t),
        3 => out.lead = try r.str(t),
        4 => out.vars = try r.list(sub.GfVar, decodeGfVar, t),
        5 => out.recheck = try r.sub(c.Btn, decodeUiBtn, t),
        6 => out.engine = try r.sub(c.Select, decodeSelState, t),
        7 => out.python = try r.sub(c.Field, decodeUiField, t),
        8 => out.browse = try r.sub(c.Btn, decodeUiBtn, t),
        9 => out.minq = try r.sub(c.Field, decodeUiField, t),
        10 => out.thresh = try r.sub(c.Field, decodeUiField, t),
        11 => out.lock = try r.sub(c.Toggle, decodeUiToggle, t),
        12 => out.hasCal = try r.boolean(t),
        13 => out.cal = try r.str(t),
        14 => out.calNote = try r.str(t),
        15 => out.note = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeGfModel(r: *wire.Reader, out: *sub.GfModel) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.sel = try r.sub(c.Select, decodeSelState, t),
        2 => out.dataset = try r.str(t),
        3 => out.running = try r.boolean(t),
        4 => out.barPct = try r.str(t),
        5 => out.barCap = try r.str(t),
        6 => out.cancel = try r.sub(c.Btn, decodeUiBtn, t),
        7 => out.hasVerdict = try r.boolean(t),
        8 => out.verdictTone = try r.str(t),
        9 => out.verdict = try r.str(t),
        10 => out.err = try r.str(t),
        11 => out.canTrain = try r.boolean(t),
        12 => out.train = try r.sub(c.Btn, decodeUiBtn, t),
        13 => out.few = try r.boolean(t),
        14 => out.fewHint = try r.str(t),
        15 => out.note = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeUiStatus(r: *wire.Reader, out: *c.Status) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.variant = try r.str(t),
        2 => out.label = try r.str(t),
        3 => out.dl = try r.str(t),
        4 => out.line = try r.str(t),
        else => try r.skip(t),
    };
}

pub fn decodeBridgeSess(r: *wire.Reader, out: *sub.BridgeSess) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.title = try r.str(t),
        2 => out.sub = try r.str(t),
        3 => out.revoke = try r.sub(c.Btn, decodeUiBtn, t),
        else => try r.skip(t),
    };
}

pub fn decodeBridgeGate(r: *wire.Reader, out: *sub.BridgeGate) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.kind = try r.str(t),
        2 => out.help = try r.str(t),
        3 => out.secret = try r.str(t),
        4 => out.uri = try r.str(t),
        5 => out.codeLabel = try r.str(t),
        6 => out.codeDL = try r.str(t),
        7 => out.confirm = try r.str(t),
        8 => out.cancel = try r.sub(c.Btn, decodeUiBtn, t),
        9 => out.burn = try r.str(t),
        10 => out.rows = try r.list(c.Status, decodeUiStatus, t),
        11 => out.note = try r.str(t),
        12 => out.btn = try r.sub(c.Btn, decodeUiBtn, t),
        13 => out.sessionsTitle = try r.str(t),
        14 => out.empty = try r.str(t),
        15 => out.sessions = try r.list(sub.BridgeSess, decodeBridgeSess, t),
        16 => out.revokeAll = try r.sub(c.Btn, decodeUiBtn, t),
        else => try r.skip(t),
    };
}

pub fn decodeBridge(r: *wire.Reader, out: *sub.Bridge) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.st = try r.sub(c.Status, decodeUiStatus, t),
        2 => out.studio = try r.sub(c.Toggle, decodeUiToggle, t),
        3 => out.tip = try r.str(t),
        4 => out.hasGate = try r.boolean(t),
        5 => out.gateTitle = try r.str(t),
        6 => out.gate = try r.sub(sub.BridgeGate, decodeBridgeGate, t),
        else => try r.skip(t),
    };
}

pub fn decodeUpdFlow(r: *wire.Reader, out: *sub.UpdFlow) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.kind = try r.str(t),
        2 => out.tone = try r.str(t),
        3 => out.text = try r.str(t),
        4 => out.hasNotes = try r.boolean(t),
        5 => out.notes = try r.str(t),
        6 => out.err = try r.str(t),
        7 => out.pct = try r.str(t),
        8 => out.cap = try r.str(t),
        9 => out.hasBtn = try r.boolean(t),
        10 => out.btn = try r.sub(c.Btn, decodeUiBtn, t),
        else => try r.skip(t),
    };
}

pub fn decodeSetBlock(r: *wire.Reader, out: *settings.Block) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.k = try r.str(t),
        2 => out.text = try r.str(t),
        3 => out.html = try r.str(t),
        4 => out.tone = try r.str(t),
        5 => out.id = try r.str(t),
        6 => out.title = try r.str(t),
        7 => out.sub = try r.str(t),
        8 => out.fld = try r.sub(c.Field, decodeUiField, t),
        9 => out.tip = try r.str(t),
        10 => out.tipSt = try r.sub(c.Tip, decodeTip, t),
        11 => out.tgl = try r.sub(c.Toggle, decodeUiToggle, t),
        12 => out.gate = try r.str(t),
        13 => out.kv = try r.sub(c.KV, decodeUiKV, t),
        14 => out.sel = try r.sub(c.Select, decodeSelState, t),
        15 => out.selLbl = try r.str(t),
        16 => out.btn = try r.sub(c.Btn, decodeUiBtn, t),
        17 => out.kids = try r.list(settings.Kid, decodeSetKid, t),
        18 => out.inputs = try r.list(settings.Input, decodeSetInput, t),
        19 => out.submit = try r.str(t),
        20 => out.subVar = try r.str(t),
        21 => out.gf = try r.sub(sub.GfCard, decodeGfCard, t),
        22 => out.gfm = try r.sub(sub.GfModel, decodeGfModel, t),
        23 => out.brg = try r.sub(sub.Bridge, decodeBridge, t),
        24 => out.upd = try r.sub(sub.UpdFlow, decodeUpdFlow, t),
        else => try r.skip(t),
    };
}

pub fn decodeSetCard(r: *wire.Reader, out: *settings.Card) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.id = try r.str(t),
        2 => out.title = try r.str(t),
        3 => out.tip = try r.str(t),
        4 => out.tipSt = try r.sub(c.Tip, decodeTip, t),
        5 => out.desc = try r.str(t),
        6 => out.st = try r.sub(settings.Status, decodeSetStatus, t),
        7 => out.tgl = try r.sub(settings.Switch, decodeSetSwitch, t),
        8 => out.blocks = try r.list(settings.Block, decodeSetBlock, t),
        else => try r.skip(t),
    };
}

pub fn decodeSetSec(r: *wire.Reader, out: *settings.Sec) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.id = try r.str(t),
        2 => out.title = try r.str(t),
        3 => out.desc = try r.str(t),
        4 => out.cards = try r.list(settings.Card, decodeSetCard, t),
        else => try r.skip(t),
    };
}

pub fn decodeSetContent(r: *wire.Reader, out: *settings.Content) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.searching = try r.boolean(t),
        2 => out.noResults = try r.str(t),
        3 => out.nav = try r.list(settings.Nav, decodeSetNav, t),
        4 => out.secs = try r.list(settings.Sec, decodeSetSec, t),
        else => try r.skip(t),
    };
}

pub fn decodeSetState(r: *wire.Reader, out: *settings.State) wire.Error!void {
    while (try r.next()) |t| switch (t.field) {
        1 => out.title = try r.str(t),
        2 => out.sub = try r.str(t),
        3 => out.available = try r.boolean(t),
        4 => out.unavailable = try r.str(t),
        5 => out.query = try r.str(t),
        6 => out.placeholder = try r.str(t),
        7 => out.content = try r.sub(settings.Content, decodeSetContent, t),
        else => try r.skip(t),
    };
}

test "schema ids are distinct" {
    try std.testing.expect(msg_ag_state != msg_logs_state);
    try std.testing.expect(msg_ag_state != msg_logs_lines);
    try std.testing.expect(msg_ag_state != msg_live_state);
    try std.testing.expect(msg_ag_state != msg_live_transport);
    try std.testing.expect(msg_ag_state != msg_live_n_p);
    try std.testing.expect(msg_ag_state != msg_live_status);
    try std.testing.expect(msg_ag_state != msg_live_decks);
    try std.testing.expect(msg_ag_state != msg_live_signals);
    try std.testing.expect(msg_ag_state != msg_live_cockpit);
    try std.testing.expect(msg_ag_state != msg_live_link);
    try std.testing.expect(msg_ag_state != msg_live_graph);
    try std.testing.expect(msg_ag_state != msg_live_perf);
    try std.testing.expect(msg_ag_state != msg_live_strip);
    try std.testing.expect(msg_ag_state != msg_mo_state);
    try std.testing.expect(msg_ag_state != msg_pub);
    try std.testing.expect(msg_ag_state != msg_pub_hero);
    try std.testing.expect(msg_ag_state != msg_set_state);
    try std.testing.expect(msg_ag_state != msg_set_content);
    try std.testing.expect(msg_ag_state != msg_set_status);
    try std.testing.expect(msg_logs_state != msg_logs_lines);
    try std.testing.expect(msg_logs_state != msg_live_state);
    try std.testing.expect(msg_logs_state != msg_live_transport);
    try std.testing.expect(msg_logs_state != msg_live_n_p);
    try std.testing.expect(msg_logs_state != msg_live_status);
    try std.testing.expect(msg_logs_state != msg_live_decks);
    try std.testing.expect(msg_logs_state != msg_live_signals);
    try std.testing.expect(msg_logs_state != msg_live_cockpit);
    try std.testing.expect(msg_logs_state != msg_live_link);
    try std.testing.expect(msg_logs_state != msg_live_graph);
    try std.testing.expect(msg_logs_state != msg_live_perf);
    try std.testing.expect(msg_logs_state != msg_live_strip);
    try std.testing.expect(msg_logs_state != msg_mo_state);
    try std.testing.expect(msg_logs_state != msg_pub);
    try std.testing.expect(msg_logs_state != msg_pub_hero);
    try std.testing.expect(msg_logs_state != msg_set_state);
    try std.testing.expect(msg_logs_state != msg_set_content);
    try std.testing.expect(msg_logs_state != msg_set_status);
    try std.testing.expect(msg_logs_lines != msg_live_state);
    try std.testing.expect(msg_logs_lines != msg_live_transport);
    try std.testing.expect(msg_logs_lines != msg_live_n_p);
    try std.testing.expect(msg_logs_lines != msg_live_status);
    try std.testing.expect(msg_logs_lines != msg_live_decks);
    try std.testing.expect(msg_logs_lines != msg_live_signals);
    try std.testing.expect(msg_logs_lines != msg_live_cockpit);
    try std.testing.expect(msg_logs_lines != msg_live_link);
    try std.testing.expect(msg_logs_lines != msg_live_graph);
    try std.testing.expect(msg_logs_lines != msg_live_perf);
    try std.testing.expect(msg_logs_lines != msg_live_strip);
    try std.testing.expect(msg_logs_lines != msg_mo_state);
    try std.testing.expect(msg_logs_lines != msg_pub);
    try std.testing.expect(msg_logs_lines != msg_pub_hero);
    try std.testing.expect(msg_logs_lines != msg_set_state);
    try std.testing.expect(msg_logs_lines != msg_set_content);
    try std.testing.expect(msg_logs_lines != msg_set_status);
    try std.testing.expect(msg_live_state != msg_live_transport);
    try std.testing.expect(msg_live_state != msg_live_n_p);
    try std.testing.expect(msg_live_state != msg_live_status);
    try std.testing.expect(msg_live_state != msg_live_decks);
    try std.testing.expect(msg_live_state != msg_live_signals);
    try std.testing.expect(msg_live_state != msg_live_cockpit);
    try std.testing.expect(msg_live_state != msg_live_link);
    try std.testing.expect(msg_live_state != msg_live_graph);
    try std.testing.expect(msg_live_state != msg_live_perf);
    try std.testing.expect(msg_live_state != msg_live_strip);
    try std.testing.expect(msg_live_state != msg_mo_state);
    try std.testing.expect(msg_live_state != msg_pub);
    try std.testing.expect(msg_live_state != msg_pub_hero);
    try std.testing.expect(msg_live_state != msg_set_state);
    try std.testing.expect(msg_live_state != msg_set_content);
    try std.testing.expect(msg_live_state != msg_set_status);
    try std.testing.expect(msg_live_transport != msg_live_n_p);
    try std.testing.expect(msg_live_transport != msg_live_status);
    try std.testing.expect(msg_live_transport != msg_live_decks);
    try std.testing.expect(msg_live_transport != msg_live_signals);
    try std.testing.expect(msg_live_transport != msg_live_cockpit);
    try std.testing.expect(msg_live_transport != msg_live_link);
    try std.testing.expect(msg_live_transport != msg_live_graph);
    try std.testing.expect(msg_live_transport != msg_live_perf);
    try std.testing.expect(msg_live_transport != msg_live_strip);
    try std.testing.expect(msg_live_transport != msg_mo_state);
    try std.testing.expect(msg_live_transport != msg_pub);
    try std.testing.expect(msg_live_transport != msg_pub_hero);
    try std.testing.expect(msg_live_transport != msg_set_state);
    try std.testing.expect(msg_live_transport != msg_set_content);
    try std.testing.expect(msg_live_transport != msg_set_status);
    try std.testing.expect(msg_live_n_p != msg_live_status);
    try std.testing.expect(msg_live_n_p != msg_live_decks);
    try std.testing.expect(msg_live_n_p != msg_live_signals);
    try std.testing.expect(msg_live_n_p != msg_live_cockpit);
    try std.testing.expect(msg_live_n_p != msg_live_link);
    try std.testing.expect(msg_live_n_p != msg_live_graph);
    try std.testing.expect(msg_live_n_p != msg_live_perf);
    try std.testing.expect(msg_live_n_p != msg_live_strip);
    try std.testing.expect(msg_live_n_p != msg_mo_state);
    try std.testing.expect(msg_live_n_p != msg_pub);
    try std.testing.expect(msg_live_n_p != msg_pub_hero);
    try std.testing.expect(msg_live_n_p != msg_set_state);
    try std.testing.expect(msg_live_n_p != msg_set_content);
    try std.testing.expect(msg_live_n_p != msg_set_status);
    try std.testing.expect(msg_live_status != msg_live_decks);
    try std.testing.expect(msg_live_status != msg_live_signals);
    try std.testing.expect(msg_live_status != msg_live_cockpit);
    try std.testing.expect(msg_live_status != msg_live_link);
    try std.testing.expect(msg_live_status != msg_live_graph);
    try std.testing.expect(msg_live_status != msg_live_perf);
    try std.testing.expect(msg_live_status != msg_live_strip);
    try std.testing.expect(msg_live_status != msg_mo_state);
    try std.testing.expect(msg_live_status != msg_pub);
    try std.testing.expect(msg_live_status != msg_pub_hero);
    try std.testing.expect(msg_live_status != msg_set_state);
    try std.testing.expect(msg_live_status != msg_set_content);
    try std.testing.expect(msg_live_status != msg_set_status);
    try std.testing.expect(msg_live_decks != msg_live_signals);
    try std.testing.expect(msg_live_decks != msg_live_cockpit);
    try std.testing.expect(msg_live_decks != msg_live_link);
    try std.testing.expect(msg_live_decks != msg_live_graph);
    try std.testing.expect(msg_live_decks != msg_live_perf);
    try std.testing.expect(msg_live_decks != msg_live_strip);
    try std.testing.expect(msg_live_decks != msg_mo_state);
    try std.testing.expect(msg_live_decks != msg_pub);
    try std.testing.expect(msg_live_decks != msg_pub_hero);
    try std.testing.expect(msg_live_decks != msg_set_state);
    try std.testing.expect(msg_live_decks != msg_set_content);
    try std.testing.expect(msg_live_decks != msg_set_status);
    try std.testing.expect(msg_live_signals != msg_live_cockpit);
    try std.testing.expect(msg_live_signals != msg_live_link);
    try std.testing.expect(msg_live_signals != msg_live_graph);
    try std.testing.expect(msg_live_signals != msg_live_perf);
    try std.testing.expect(msg_live_signals != msg_live_strip);
    try std.testing.expect(msg_live_signals != msg_mo_state);
    try std.testing.expect(msg_live_signals != msg_pub);
    try std.testing.expect(msg_live_signals != msg_pub_hero);
    try std.testing.expect(msg_live_signals != msg_set_state);
    try std.testing.expect(msg_live_signals != msg_set_content);
    try std.testing.expect(msg_live_signals != msg_set_status);
    try std.testing.expect(msg_live_cockpit != msg_live_link);
    try std.testing.expect(msg_live_cockpit != msg_live_graph);
    try std.testing.expect(msg_live_cockpit != msg_live_perf);
    try std.testing.expect(msg_live_cockpit != msg_live_strip);
    try std.testing.expect(msg_live_cockpit != msg_mo_state);
    try std.testing.expect(msg_live_cockpit != msg_pub);
    try std.testing.expect(msg_live_cockpit != msg_pub_hero);
    try std.testing.expect(msg_live_cockpit != msg_set_state);
    try std.testing.expect(msg_live_cockpit != msg_set_content);
    try std.testing.expect(msg_live_cockpit != msg_set_status);
    try std.testing.expect(msg_live_link != msg_live_graph);
    try std.testing.expect(msg_live_link != msg_live_perf);
    try std.testing.expect(msg_live_link != msg_live_strip);
    try std.testing.expect(msg_live_link != msg_mo_state);
    try std.testing.expect(msg_live_link != msg_pub);
    try std.testing.expect(msg_live_link != msg_pub_hero);
    try std.testing.expect(msg_live_link != msg_set_state);
    try std.testing.expect(msg_live_link != msg_set_content);
    try std.testing.expect(msg_live_link != msg_set_status);
    try std.testing.expect(msg_live_graph != msg_live_perf);
    try std.testing.expect(msg_live_graph != msg_live_strip);
    try std.testing.expect(msg_live_graph != msg_mo_state);
    try std.testing.expect(msg_live_graph != msg_pub);
    try std.testing.expect(msg_live_graph != msg_pub_hero);
    try std.testing.expect(msg_live_graph != msg_set_state);
    try std.testing.expect(msg_live_graph != msg_set_content);
    try std.testing.expect(msg_live_graph != msg_set_status);
    try std.testing.expect(msg_live_perf != msg_live_strip);
    try std.testing.expect(msg_live_perf != msg_mo_state);
    try std.testing.expect(msg_live_perf != msg_pub);
    try std.testing.expect(msg_live_perf != msg_pub_hero);
    try std.testing.expect(msg_live_perf != msg_set_state);
    try std.testing.expect(msg_live_perf != msg_set_content);
    try std.testing.expect(msg_live_perf != msg_set_status);
    try std.testing.expect(msg_live_strip != msg_mo_state);
    try std.testing.expect(msg_live_strip != msg_pub);
    try std.testing.expect(msg_live_strip != msg_pub_hero);
    try std.testing.expect(msg_live_strip != msg_set_state);
    try std.testing.expect(msg_live_strip != msg_set_content);
    try std.testing.expect(msg_live_strip != msg_set_status);
    try std.testing.expect(msg_mo_state != msg_pub);
    try std.testing.expect(msg_mo_state != msg_pub_hero);
    try std.testing.expect(msg_mo_state != msg_set_state);
    try std.testing.expect(msg_mo_state != msg_set_content);
    try std.testing.expect(msg_mo_state != msg_set_status);
    try std.testing.expect(msg_pub != msg_pub_hero);
    try std.testing.expect(msg_pub != msg_set_state);
    try std.testing.expect(msg_pub != msg_set_content);
    try std.testing.expect(msg_pub != msg_set_status);
    try std.testing.expect(msg_pub_hero != msg_set_state);
    try std.testing.expect(msg_pub_hero != msg_set_content);
    try std.testing.expect(msg_pub_hero != msg_set_status);
    try std.testing.expect(msg_set_state != msg_set_content);
    try std.testing.expect(msg_set_state != msg_set_status);
    try std.testing.expect(msg_set_content != msg_set_status);
}
