package webui

// Virtual shell + headless UI session. A virtualShell satisfies the shell seam but drives no
// native window: setHTML/eval emit the Go-rendered document + patch stream to a sink, and remote
// input is replayed through onAction. remoteui_host.go builds one per remote-library session so a
// paired peer mirrors this instance's Library tab pixel-for-pixel without touching the visible
// window. Renders go through the SAME pipeline as the real UI (mainHTML/patchMain/eval queue) -
// no forked renderers.

import (
	"strings"
	"sync"
	"time"

	"rave.page/mate/internal/ui"
)

const (
	// vsActQueueCap bounds queued remote input events. Policy: drop-newest (a flooding
	// controller loses its own extra clicks; this instance never accumulates them).
	vsActQueueCap = 256
)

type virtualShell struct {
	onAction func(string)
	emitHTML func(string) // full-document loads (setHTML / initial doc)
	// emitEval carries page evals pre-batched by the eval flusher. Security: every script is
	// Go-generated by THIS instance's renderers (same contract as ui.go's eval queue - never
	// remote/untrusted input); the mirror side executes it inside a sandboxed iframe only after
	// the Ed25519-authenticated, per-frame-MAC'd peer link delivered it (trusted-on-pair, the
	// same trust domain remotectl already grants a paired peer).
	emitEval func(string)

	acts chan string // remote input → onAction, serialized (mirrors cgoShell.actWorker)

	closeOnce sync.Once
	done      chan struct{}
}

func newVirtualShell(onAction func(string), emitHTML, emitEval func(string)) *virtualShell {
	s := &virtualShell{
		onAction: onAction, emitHTML: emitHTML, emitEval: emitEval,
		acts: make(chan string, vsActQueueCap), done: make(chan struct{}),
	}
	go s.actWorker()
	return s
}

// actWorker drains remote input serialized in arrival order (same contract as cgoShell).
func (s *virtualShell) actWorker() {
	for {
		select {
		case <-s.done:
			return
		case p := <-s.acts:
			if s.onAction != nil {
				s.onAction(p)
			}
		}
	}
}

// post queues one remote input payload; false when the queue is full (dropped) or closed.
func (s *virtualShell) post(payload string) bool {
	select {
	case <-s.done:
		return false
	default:
	}
	select {
	case s.acts <- payload:
		return true
	default:
		return false // cap vsActQueueCap, drop-newest
	}
}

func (s *virtualShell) run(initialHTML string, _ bool) { s.emitHTML(initialHTML) }
func (s *virtualShell) setHTML(html string)            { s.emitHTML(html) }
func (s *virtualShell) eval(js string)                 { s.emitEval(js) }
func (s *virtualShell) resize(int, int)                {}
func (s *virtualShell) show()                          {}
func (s *virtualShell) terminate()                     { s.closeOnce.Do(func() { close(s.done) }) }
func (s *virtualShell) hwnd() uintptr                  { return 0 }

// newHeadlessUI builds a windowless UI over the shared Services whose renders emit into a
// virtual shell. Pinned to the Library tab (the remote-mirror surface); everything else - state,
// dispatch, eval queue - is the normal per-*UI pipeline. Caller must Stop() it and then
// releaseUIState() to drop its per-UI package-map entries.
func newHeadlessUI(svc ui.Services, emitHTML, emitEval func(string)) *UI {
	u := &UI{svc: svc, log: svc.Log, active: "library", pinnedTab: "library",
		started: time.Now(), stop: make(chan struct{}),
		logBus: "app", logLevel: "all", logAutoscroll: true, evalKick: make(chan struct{}, 1),
		actQ: make(chan actMsg, maxActQueue)}
	vs := newVirtualShell(u.onAction, emitHTML, emitEval)
	u.shell = vs
	go u.evalFlusher()
	go u.actWorker()  // acts from the virtual shell run here, not on its input pump
	u.libWatchStart() // mirrors track peer/local cue edits too (Stop() unsubscribes)
	return u
}

// headlessDocHTML is the initial document for a headless session: the normal shell document
// minus the nav rail (the mirror embeds only the content region; #main + #__modal keep their
// ids so every patch/eval targets the same nodes as on a real window).
func (u *UI) headlessDocHTML() string {
	var b []byte
	b = append(b, "<!doctype html><html lang=en><head><meta charset=utf-8>"...)
	b = append(b, `<meta name=viewport content="width=device-width,initial-scale=1">`...)
	b = append(b, "<title>rave-mate remote</title><style>"...)
	b = append(b, buildCSS()...)
	b = append(b, "</style></head><body><main id=main>"...)
	b = append(b, u.mainHTML()...)
	b = append(b, `</main><div id=__modal></div></body></html>`...)
	return string(b)
}

// releaseUIState drops a retired UI's entries from the per-*UI package maps (they would
// otherwise leak one entry per remote session). Call after Stop().
func releaseUIState(u *UI) {
	libStMu.Lock()
	delete(libSts, u)
	libStMu.Unlock()
	mpMu.Lock()
	delete(mpInstances, u)
	mpMu.Unlock()
	mpMoveMu.Lock() // busy flags self-delete when their worker drains
	for k := range mpMovePend {
		if k.u == u {
			delete(mpMovePend, k)
		}
	}
	mpMoveMu.Unlock()
	mpMediaFS.releaseMediaOwner(u)
	mirrorMu.Lock()
	delete(mirrorSts, u)
	mirrorMu.Unlock()
	pubRemoteMu.Lock()
	delete(pubRemoteSts, u)
	pubRemoteMu.Unlock()
	cpvMu.Lock()
	delete(cpvMap, u)
	cpvMu.Unlock()
	moMu.Lock()
	delete(moMap, u)
	moMu.Unlock()
	vrmMu.Lock()
	delete(vrmMap, u)
	vrmMu.Unlock()
}

// virtual reports whether this UI renders into a virtual shell (headless session).
func (u *UI) virtual() bool {
	_, ok := u.shell.(*virtualShell)
	return ok
}

// Acts a headless session refuses (picker precedent, pick_actions.go): each opens an OS
// surface - file/folder in Explorer, external app, browser window/sign-in - which would land
// on the CONTROLLED machine's desktop, not the controller's.
var (
	virtualDeniedExact = map[string]bool{
		"open-url":               true,
		"auth-login":             true, // browser sign-in
		"settings-rbmidi-folder": true,
		"ovl-png-open":           true,
		"ovl-np-open":            true,
		"settings-twitch-signin": true, // device-auth: opens verification URL
		"settings-gh-device":     true,
		"world-gh-device":        true,
	}
	virtualDeniedPrefix = []string{
		"mp-openext:", "mp-reveal:",
		"lib-opendir:", "lib-reveal:", "lib-openext:", "lib-bk-open:",
		"pub-open:", "pub-reveal:",
		"settings-open:",
	}
)

// virtualDenied reports whether a headless session must refuse act.
func virtualDenied(act string) bool {
	if virtualDeniedExact[act] {
		return true
	}
	for _, p := range virtualDeniedPrefix {
		if strings.HasPrefix(act, p) {
			return true
		}
	}
	return false
}
