// Code generated by internal/zigui/wiregen. DO NOT EDIT.

package webui

import "rave.page/mate/internal/zigui"

// RZW1 state-wire encoders (the binary v2 path; the JSON v1 path stays for fallback).
// Field numbers + hash come from internal/zigui/wiregen/schema.go - regenerate, never edit.
const (
	wireSchemaHash       uint32 = 0xf842f2ca
	wireMsgAgState       uint16 = 1  // App Groups tab (full view + the #appgroups-body fragment share this state)
	wireMsgLogsState     uint16 = 2  // Logs tab (full view)
	wireMsgLogsLines     uint16 = 3  // #log-view inner fragment (filter change + ~1 Hz tick)
	wireMsgLiveState     uint16 = 10 // Live tab - full cockpit
	wireMsgLiveTransport uint16 = 11 // #live-transport fragment
	wireMsgLiveNP        uint16 = 12 // #live-np fragment
	wireMsgLiveStatus    uint16 = 13 // #live-status fragment
	wireMsgLiveDecks     uint16 = 14 // #live-decks fragment
	wireMsgLiveSignals   uint16 = 15 // #live-signals fragment
	wireMsgLiveCockpit   uint16 = 16 // #live-cockpit fragment
	wireMsgLiveLink      uint16 = 17 // #live-ablelink fragment
	wireMsgLiveGraph     uint16 = 18 // #live-net + #live-tim fragments
	wireMsgLivePerf      uint16 = 19 // #live-perf2 fragment
	wireMsgLiveStrip     uint16 = 20 // #live-strip fragment
	wireMsgMoState       uint16 = 21 // Motion tab (full view + the #mo-body fragment share this state)
	wireMsgPub           uint16 = 22 // Publish tab (full view)
	wireMsgPubHero       uint16 = 23 // #pub-hero fragment (~1 Hz tick)
	wireMsgSetState      uint16 = 24 // Settings tab (full view)
	wireMsgSetContent    uint16 = 25 // #set-content pane (sub-tab switch + search)
	wireMsgSetStatus     uint16 = 26 // one #stset-<id> status fragment (settings tick)
)

func (v agApp) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Base)
	w.Bool(2, v.Elevated)
}

func (v agGroup) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.ID)
	w.Str(2, v.Name)
	w.Str(3, v.Up)
	w.Str(4, v.Variant)
	w.List(5, len(v.Apps), func(i int) { v.Apps[i].encodeWire(w) })
}

func (v agState) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Title)
	w.Str(2, v.Subtitle)
	w.Bool(3, v.Available)
	w.Str(4, v.Unavailable)
	w.Str(5, v.Empty)
	w.Str(6, v.Admin)
	w.Str(7, v.Launch)
	w.List(8, len(v.Groups), func(i int) { v.Groups[i].encodeWire(w) })
}

func (v selRow) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Val)
	w.Str(2, v.Label)
	w.Str(3, v.Sub)
	w.Str(4, v.Badge)
	w.Bool(5, v.Cur)
}

func (v selState) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.ID)
	w.Str(2, v.Label)
	w.Str(3, v.CurLabel)
	w.Bool(4, v.Open)
	w.Str(5, v.Filter)
	w.List(6, len(v.Rows), func(i int) { v.Rows[i].encodeWire(w) })
}

func (v logsTab) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Val)
	w.Str(2, v.Label)
}

func (v logsEntry) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Time)
	w.Str(2, v.Lvl)
	w.Str(3, v.Cls)
	w.Str(4, v.Src)
	w.Str(5, v.Msg)
	w.Str(6, v.Fields)
}

func (v logsLines) encodeWire(w *zigui.WireWriter) {
	w.Bool(1, v.Wired)
	w.Str(2, v.NoBus)
	w.Str(3, v.NoEntries)
	w.List(4, len(v.Entries), func(i int) { v.Entries[i].encodeWire(w) })
}

func (v logsState) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Title)
	w.Str(2, v.Sub)
	w.Bool(3, v.ShowBus)
	w.Str(4, v.BusActive)
	w.List(5, len(v.BusItems), func(i int) { v.BusItems[i].encodeWire(w) })
	w.Struct(6, func() { v.Level.encodeWire(w) })
	w.Struct(7, func() { v.Source.encodeWire(w) })
	w.Str(8, v.SearchLabel)
	w.Str(9, v.SearchPH)
	w.Str(10, v.SearchVal)
	w.Str(11, v.AutoLabel)
	w.Str(12, v.AutoDL)
	w.Bool(13, v.AutoOn)
	w.Str(14, v.Copy)
	w.Str(15, v.Clear)
	w.Str(16, v.Tailing)
	w.Struct(17, func() { v.Lines.encodeWire(w) })
}

func (v liveTransportSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.StreamHint)
	w.Str(2, v.StreamLabel)
	w.Str(3, v.DotVar)
	w.Str(4, v.State)
	w.Str(5, v.MetaOnly)
	w.Str(6, v.PauseLabel)
	w.Str(7, v.PauseHint)
	w.Bool(8, v.Paused)
	w.Bool(9, v.HasRec)
	w.Str(10, v.RecHint)
	w.Str(11, v.RecLabel)
	w.Str(12, v.RecBtn)
	w.Str(13, v.RecState)
	w.Bool(14, v.HasTC)
	w.Str(15, v.TCLabel)
	w.Str(16, v.TC)
	w.Str(17, v.StartLbl)
	w.Str(18, v.StopLbl)
}

func (v liveNPSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Line1)
	w.Str(2, v.Line2)
}

func (v liveKV) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.K)
	w.Str(2, v.KL)
	w.Str(3, v.V)
}

func (v liveStatusSt) encodeWire(w *zigui.WireWriter) {
	w.List(1, len(v.Rows), func(i int) { v.Rows[i].encodeWire(w) })
}

func (v liveDeck) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Cls)
	w.Str(2, v.Name)
	w.Str(3, v.Title)
	w.Str(4, v.Meta)
	w.Str(5, v.Via)
}

func (v liveDecksSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Note)
	w.List(2, len(v.Decks), func(i int) { v.Decks[i].encodeWire(w) })
}

func (v liveSignalsSt) encodeWire(w *zigui.WireWriter) {
	w.List(1, len(v.Rows), func(i int) { v.Rows[i].encodeWire(w) })
}

func (v liveCockpitRow) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Variant)
	w.Str(2, v.Name)
	w.Str(3, v.State)
	w.Str(4, v.StreamLbl)
	w.Str(5, v.StreamAct)
	w.Str(6, v.RecLbl)
	w.Str(7, v.RecAct)
}

func (v liveCockpitSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Empty)
	w.Str(2, v.Caption)
	w.List(3, len(v.Rows), func(i int) { v.Rows[i].encodeWire(w) })
}

func (v liveSRow) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Variant)
	w.Str(2, v.Label)
	w.Str(3, v.DL)
	w.Str(4, v.Line)
}

func (v liveLinkSt) encodeWire(w *zigui.WireWriter) {
	w.Bool(1, v.Available)
	w.Struct(2, func() { v.Backend.encodeWire(w) })
	w.StrAlways(3, v.Fill)
	w.Str(4, v.Cap)
	w.Struct(5, func() { v.Session.encodeWire(w) })
	w.Str(6, v.ResyncLbl)
	w.List(7, len(v.Sources), func(i int) { v.Sources[i].encodeWire(w) })
}

func (v liveGraphSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Tooltip)
	w.Str(2, v.Legend)
	w.Str(3, v.Graph)
}

func (v livePerfSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Tooltip)
	w.Str(2, v.CPULeg)
	w.Str(3, v.CPUGraph)
	w.Str(4, v.RAMLeg)
	w.Str(5, v.RAMGraph)
	w.Str(6, v.Head)
	w.Str(7, v.HeadColor)
}

func (v liveStripSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Left)
	w.Str(2, v.Center)
	w.Str(3, v.Right)
}

func (v liveState) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Title)
	w.Str(2, v.Sub)
	w.Struct(3, func() { v.Transport.encodeWire(w) })
	w.Struct(4, func() { v.NP.encodeWire(w) })
	w.Str(5, v.StatusTitle)
	w.Struct(6, func() { v.Status.encodeWire(w) })
	w.Str(7, v.DecksTitle)
	w.Struct(8, func() { v.Decks.encodeWire(w) })
	w.Bool(9, v.HasSignals)
	w.Str(10, v.SignalsTitle)
	w.Str(11, v.SignalsTip)
	w.Struct(12, func() { v.Signals.encodeWire(w) })
	w.Bool(13, v.HasCockpit)
	w.Str(14, v.CockpitTitle)
	w.Struct(15, func() { v.Cockpit.encodeWire(w) })
	w.Bool(16, v.HasLink)
	w.Str(17, v.LinkTitle)
	w.Struct(18, func() { v.Link.encodeWire(w) })
	w.Bool(19, v.HasNet)
	w.Str(20, v.NetTitle)
	w.Str(21, v.NetTip)
	w.Struct(22, func() { v.Net.encodeWire(w) })
	w.Str(23, v.TimTitle)
	w.Str(24, v.TimTip)
	w.Struct(25, func() { v.Tim.encodeWire(w) })
	w.Bool(26, v.HasPerf)
	w.Str(27, v.PerfTitle)
	w.Str(28, v.PerfTip)
	w.Struct(29, func() { v.Perf.encodeWire(w) })
	w.Struct(30, func() { v.Strip.encodeWire(w) })
}

func (v moCamRow) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Group)
	w.Bool(2, v.ShowGroup)
	w.Str(3, v.Act)
	w.Bool(4, v.Sel)
	w.Str(5, v.Name)
	w.Str(6, v.Meta)
}

func (v moCamSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Unavailable)
	w.List(2, len(v.Rows), func(i int) { v.Rows[i].encodeWire(w) })
	w.Str(3, v.Empty)
	w.Str(4, v.ReloadLbl)
	w.Str(5, v.OrganizeLbl)
	w.Str(6, v.DJLbl)
	w.Str(7, v.PreviewLbl)
	w.Str(8, v.Tip)
	w.Str(9, v.View)
	w.Str(10, v.Hint)
	w.Str(11, v.Info)
	w.Str(12, v.PlayBtn)
	w.Str(13, v.LoadLbl)
	w.Str(14, v.CopyLbl)
}

func (v moRecRow) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Name)
	w.Str(2, v.Act)
	w.Bool(3, v.Sel)
}

func (v moAvatarSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Label)
	w.Struct(2, func() { v.Sel.encodeWire(w) })
	w.Str(3, v.ImportLbl)
	w.Str(4, v.SyncLbl)
	w.Str(5, v.Info)
}

func (v moSliderSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Label)
	w.Str(2, v.DL)
	w.Str(3, v.Act)
	w.Str(4, v.Unit)
	w.StrAlways(5, v.UnitJS)
	w.StrAlways(6, v.MinS)
	w.StrAlways(7, v.MaxS)
	w.StrAlways(8, v.StepS)
	w.StrAlways(9, v.ValS)
}

func (v moToggleSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Label)
	w.Str(2, v.DL)
	w.Str(3, v.Act)
	w.Bool(4, v.On)
}

func (v moStudioSt) encodeWire(w *zigui.WireWriter) {
	w.List(1, len(v.Recs), func(i int) { v.Recs[i].encodeWire(w) })
	w.Str(2, v.Empty)
	w.Str(3, v.RefreshLbl)
	w.Str(4, v.ExportLbl)
	w.Str(5, v.RenderLbl)
	w.Str(6, v.PCViewLbl)
	w.Str(7, v.RenderProg)
	w.Struct(8, func() { v.Avatar.encodeWire(w) })
	w.Str(9, v.PreviewLbl)
	w.Str(10, v.Tip)
	w.Str(11, v.View)
	w.Str(12, v.Hint)
	w.Str(13, v.Time)
	w.Struct(14, func() { v.Scrub.encodeWire(w) })
	w.Str(15, v.PlayLbl)
	w.Str(16, v.StopLbl)
	w.Struct(17, func() { v.Loop.encodeWire(w) })
	w.Struct(18, func() { v.OSC.encodeWire(w) })
	w.Struct(19, func() { v.VMC.encodeWire(w) })
	w.Struct(20, func() { v.Model.encodeWire(w) })
	w.Bool(21, v.ModelOn)
	w.Bool(22, v.HasDyn)
	w.Str(23, v.PhysNote)
	w.Struct(24, func() { v.Phys.encodeWire(w) })
	w.Struct(25, func() { v.Rest.encodeWire(w) })
	w.Struct(26, func() { v.Marks.encodeWire(w) })
	w.Struct(27, func() { v.PC.encodeWire(w) })
	w.Bool(28, v.PCOn)
	w.Struct(29, func() { v.PCDensity.encodeWire(w) })
	w.Struct(30, func() { v.PCColor.encodeWire(w) })
	w.Str(31, v.PCNote)
	w.Str(32, v.PCExportLbl)
	w.Str(33, v.VMCHelp)
}

func (v moState) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Title)
	w.Str(2, v.Sub)
	w.Str(3, v.Section)
	w.Str(4, v.TabCam)
	w.Str(5, v.TabStudio)
	if v.Cam != nil {
		w.OptStruct(6, func() { v.Cam.encodeWire(w) })
	}
	if v.Studio != nil {
		w.OptStruct(7, func() { v.Studio.encodeWire(w) })
	}
}

func (v pubBadgeSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Key)
	w.Str(2, v.DL)
	w.Str(3, v.Variant)
	w.Str(4, v.Line)
}

func (v pubBarSt) encodeWire(w *zigui.WireWriter) {
	w.Bool(1, v.Show)
	w.Str(2, v.Pct)
	w.Str(3, v.Cap)
}

func (v pubNpSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Label)
	w.Str(2, v.Title)
	w.Str(3, v.Meta)
	w.Str(4, v.State)
	w.Struct(5, func() { v.Bar.encodeWire(w) })
}

func (v pubPlayerSt) encodeWire(w *zigui.WireWriter) {
	w.Bool(1, v.Show)
	w.Str(2, v.Label)
	w.Str(3, v.Pos)
	w.Struct(4, func() { v.Bar.encodeWire(w) })
}

func (v pubHeroSt) encodeWire(w *zigui.WireWriter) {
	w.Bool(1, v.Show)
	w.Struct(2, func() { v.Rec.encodeWire(w) })
	w.Struct(3, func() { v.Cap.encodeWire(w) })
	w.Struct(4, func() { v.Obs.encodeWire(w) })
	w.Str(5, v.Finish)
	w.Struct(6, func() { v.NP.encodeWire(w) })
	w.Struct(7, func() { v.Player.encodeWire(w) })
}

func (v pubSetRowSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.ID)
	w.Str(2, v.Title)
	w.Str(3, v.Sub)
	w.Bool(4, v.Sel)
	w.Str(5, v.Rename)
}

func (v pubListSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Empty)
	w.Str(2, v.Count)
	w.List(3, len(v.Rows), func(i int) { v.Rows[i].encodeWire(w) })
}

func (v uiBtn) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Label)
	w.Str(2, v.Variant)
	w.Str(3, v.Act)
	w.Str(4, v.Val)
}

func (v pubCapSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Caption)
	w.List(2, len(v.Btns), func(i int) { v.Btns[i].encodeWire(w) })
	w.Struct(3, func() { v.Menu.encodeWire(w) })
}

func (v pubLooseSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Count)
	w.Str(2, v.Desc)
	w.List(3, len(v.Caps), func(i int) { v.Caps[i].encodeWire(w) })
}

func (v pubCapturesSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Player)
	w.Str(2, v.Empty)
	w.List(3, len(v.Caps), func(i int) { v.Caps[i].encodeWire(w) })
}

func (v pubTrackSt) encodeWire(w *zigui.WireWriter) {
	w.Uint(1, uint64(v.Num))
	w.Str(2, v.Label)
	w.Str(3, v.Off)
	w.Str(4, v.Lead)
	w.Str(5, v.LeadTip)
	w.Bool(6, v.Checked)
	w.Str(7, v.Path)
	w.Str(8, v.Ctx)
	w.Str(9, v.OffAct)
	w.Str(10, v.OffDL)
}

func (v pubBatchSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Count)
	w.List(2, len(v.Btns), func(i int) { v.Btns[i].encodeWire(w) })
}

func (v pubTracklistSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Empty)
	w.Str(2, v.Resolving)
	w.Bool(3, v.Editable)
	w.Str(4, v.OffTip)
	w.List(5, len(v.Rows), func(i int) { v.Rows[i].encodeWire(w) })
	w.Bool(6, v.ShowFix)
	w.Struct(7, func() { v.Fix.encodeWire(w) })
	w.Str(8, v.Help)
	w.Str(9, v.Unres)
	w.Struct(10, func() { v.Batch.encodeWire(w) })
}

func (v pubDetailSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.CardTitle)
	w.Bool(2, v.Sel)
	w.Str(3, v.Hint)
	w.Str(4, v.Player)
	w.Struct(5, func() { v.Loose.encodeWire(w) })
	w.Str(6, v.Name)
	w.Str(7, v.Meta)
	w.List(8, len(v.Actions), func(i int) { v.Actions[i].encodeWire(w) })
	w.Str(9, v.Active)
	w.Str(10, v.CapsLbl)
	w.Str(11, v.TracksLbl)
	w.Struct(12, func() { v.Captures.encodeWire(w) })
	w.Struct(13, func() { v.Tracklist.encodeWire(w) })
}

func (v pubBodySt) encodeWire(w *zigui.WireWriter) {
	w.Struct(1, func() { v.Hero.encodeWire(w) })
	w.Struct(2, func() { v.List.encodeWire(w) })
	w.Struct(3, func() { v.Detail.encodeWire(w) })
}

func (v pubSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Title)
	w.Str(2, v.Sub)
	w.Str(3, v.Switcher)
	w.Bool(4, v.Available)
	w.Str(5, v.Unavailable)
	w.Struct(6, func() { v.Body.encodeWire(w) })
}

func (v setNavSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.ID)
	w.Str(2, v.Title)
	w.Str(3, v.Agg)
	w.Bool(4, v.Active)
}

func (v tipChipSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Text)
	w.Bool(2, v.Sep)
}

func (v tipKbSt) encodeWire(w *zigui.WireWriter) {
	w.Bool(1, v.HasGroup)
	w.Str(2, v.Group)
	w.List(3, len(v.Chips), func(i int) { v.Chips[i].encodeWire(w) })
	w.Str(4, v.Verb)
	w.Str(5, v.Rest)
}

func (v tipLinkSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Label)
	w.Str(2, v.URL)
}

func (v tipSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.ID)
	w.Str(2, v.Title)
	w.List(3, len(v.Keys), func(i int) { v.Keys[i].encodeWire(w) })
	w.StrList(4, v.Paras)
	w.List(5, len(v.Links), func(i int) { v.Links[i].encodeWire(w) })
}

func (v setStatusSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.V)
	w.Str(2, v.T)
}

func (v setSwitchSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Label)
	w.Bool(2, v.On)
	w.Str(3, v.Gate)
}

func (v uiField) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Label)
	w.Str(2, v.DL)
	w.Str(3, v.Act)
	w.Str(4, v.Value)
	w.Str(5, v.Type)
	w.Str(6, v.PH)
}

func (v uiToggle) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Label)
	w.Str(2, v.DL)
	w.Str(3, v.Act)
	w.Bool(4, v.On)
}

func (v uiKV) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Label)
	w.Str(2, v.DL)
	w.Str(3, v.Value)
}

func (v setKid) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.K)
	if v.Fld != nil {
		w.OptStruct(2, func() { v.Fld.encodeWire(w) })
	}
	w.Str(3, v.Tip)
	if v.TipS != nil {
		w.OptStruct(4, func() { v.TipS.encodeWire(w) })
	}
	if v.Sel != nil {
		w.OptStruct(5, func() { v.Sel.encodeWire(w) })
	}
	w.Str(6, v.SelLbl)
	if v.Btn != nil {
		w.OptStruct(7, func() { v.Btn.encodeWire(w) })
	}
}

func (v setInput) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Type)
	w.Str(2, v.Name)
	w.Str(3, v.PH)
}

func (v gfBtn) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Label)
	w.Str(2, v.Variant)
	w.Str(3, v.Act)
	w.Str(4, v.Gate)
}

func (v gfVarSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Key)
	w.Str(2, v.Tone)
	w.Str(3, v.Line)
	w.List(4, len(v.Btns), func(i int) { v.Btns[i].encodeWire(w) })
	w.Bool(5, v.HasNote)
	w.Str(6, v.Note)
}

func (v gfCardSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.LeadKind)
	w.Str(2, v.LeadTone)
	w.Str(3, v.Lead)
	w.List(4, len(v.Vars), func(i int) { v.Vars[i].encodeWire(w) })
	w.Struct(5, func() { v.Recheck.encodeWire(w) })
	w.Struct(6, func() { v.Engine.encodeWire(w) })
	w.Struct(7, func() { v.Python.encodeWire(w) })
	w.Struct(8, func() { v.Browse.encodeWire(w) })
	w.Struct(9, func() { v.MinQ.encodeWire(w) })
	w.Struct(10, func() { v.Thresh.encodeWire(w) })
	w.Struct(11, func() { v.Lock.encodeWire(w) })
	w.Bool(12, v.HasCal)
	w.Str(13, v.Cal)
	w.Str(14, v.CalNote)
	w.Str(15, v.Note)
}

func (v gfModelSt) encodeWire(w *zigui.WireWriter) {
	w.Struct(1, func() { v.Sel.encodeWire(w) })
	w.Str(2, v.Dataset)
	w.Bool(3, v.Running)
	w.Str(4, v.BarPct)
	w.Str(5, v.BarCap)
	w.Struct(6, func() { v.Cancel.encodeWire(w) })
	w.Bool(7, v.HasVerdict)
	w.Str(8, v.VerdictTone)
	w.Str(9, v.Verdict)
	w.Str(10, v.Err)
	w.Bool(11, v.CanTrain)
	w.Struct(12, func() { v.Train.encodeWire(w) })
	w.Bool(13, v.Few)
	w.Str(14, v.FewHint)
	w.Str(15, v.Note)
}

func (v uiStatus) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Variant)
	w.Str(2, v.Label)
	w.Str(3, v.DL)
	w.Str(4, v.Line)
}

func (v bridgeSessSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Title)
	w.Str(2, v.Sub)
	w.Struct(3, func() { v.Revoke.encodeWire(w) })
}

func (v bridgeGateSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Kind)
	w.Str(2, v.Help)
	w.Str(3, v.Secret)
	w.Str(4, v.URI)
	w.Str(5, v.CodeLabel)
	w.Str(6, v.CodeDL)
	w.Str(7, v.Confirm)
	w.Struct(8, func() { v.Cancel.encodeWire(w) })
	w.Str(9, v.Burn)
	w.List(10, len(v.Rows), func(i int) { v.Rows[i].encodeWire(w) })
	w.Str(11, v.Note)
	w.Struct(12, func() { v.Btn.encodeWire(w) })
	w.Str(13, v.SessionsTitle)
	w.Str(14, v.Empty)
	w.List(15, len(v.Sessions), func(i int) { v.Sessions[i].encodeWire(w) })
	w.Struct(16, func() { v.RevokeAll.encodeWire(w) })
}

func (v bridgeSt) encodeWire(w *zigui.WireWriter) {
	w.Struct(1, func() { v.St.encodeWire(w) })
	w.Struct(2, func() { v.Studio.encodeWire(w) })
	w.Str(3, v.Tip)
	w.Bool(4, v.HasGate)
	w.Str(5, v.GateTitle)
	w.Struct(6, func() { v.Gate.encodeWire(w) })
}

func (v updFlowSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Kind)
	w.Str(2, v.Tone)
	w.Str(3, v.Text)
	w.Bool(4, v.HasNotes)
	w.Str(5, v.Notes)
	w.Str(6, v.Err)
	w.Str(7, v.Pct)
	w.Str(8, v.Cap)
	w.Bool(9, v.HasBtn)
	w.Struct(10, func() { v.Btn.encodeWire(w) })
}

func (v setBlock) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.K)
	w.Str(2, v.Text)
	w.Str(3, v.HTML)
	w.Str(4, v.Tone)
	w.Str(5, v.ID)
	w.Str(6, v.Title)
	w.Str(7, v.Sub)
	if v.Fld != nil {
		w.OptStruct(8, func() { v.Fld.encodeWire(w) })
	}
	w.Str(9, v.Tip)
	if v.TipS != nil {
		w.OptStruct(10, func() { v.TipS.encodeWire(w) })
	}
	if v.Tgl != nil {
		w.OptStruct(11, func() { v.Tgl.encodeWire(w) })
	}
	w.Str(12, v.Gate)
	if v.KV != nil {
		w.OptStruct(13, func() { v.KV.encodeWire(w) })
	}
	if v.Sel != nil {
		w.OptStruct(14, func() { v.Sel.encodeWire(w) })
	}
	w.Str(15, v.SelLbl)
	if v.Btn != nil {
		w.OptStruct(16, func() { v.Btn.encodeWire(w) })
	}
	w.List(17, len(v.Kids), func(i int) { v.Kids[i].encodeWire(w) })
	w.List(18, len(v.Inputs), func(i int) { v.Inputs[i].encodeWire(w) })
	w.Str(19, v.Submit)
	w.Str(20, v.SubVar)
	if v.GF != nil {
		w.OptStruct(21, func() { v.GF.encodeWire(w) })
	}
	if v.GFM != nil {
		w.OptStruct(22, func() { v.GFM.encodeWire(w) })
	}
	if v.Brg != nil {
		w.OptStruct(23, func() { v.Brg.encodeWire(w) })
	}
	if v.Upd != nil {
		w.OptStruct(24, func() { v.Upd.encodeWire(w) })
	}
}

func (v setCardSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.ID)
	w.Str(2, v.Title)
	w.Str(3, v.Tip)
	if v.TipS != nil {
		w.OptStruct(4, func() { v.TipS.encodeWire(w) })
	}
	w.Str(5, v.Desc)
	w.Struct(6, func() { v.St.encodeWire(w) })
	if v.Tgl != nil {
		w.OptStruct(7, func() { v.Tgl.encodeWire(w) })
	}
	w.List(8, len(v.Blocks), func(i int) { v.Blocks[i].encodeWire(w) })
}

func (v setSecSt) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.ID)
	w.Str(2, v.Title)
	w.Str(3, v.Desc)
	w.List(4, len(v.Cards), func(i int) { v.Cards[i].encodeWire(w) })
}

func (v setContentSt) encodeWire(w *zigui.WireWriter) {
	w.Bool(1, v.Searching)
	w.Str(2, v.NoResults)
	w.List(3, len(v.Nav), func(i int) { v.Nav[i].encodeWire(w) })
	w.List(4, len(v.Secs), func(i int) { v.Secs[i].encodeWire(w) })
}

func (v setState) encodeWire(w *zigui.WireWriter) {
	w.Str(1, v.Title)
	w.Str(2, v.Sub)
	w.Bool(3, v.Available)
	w.Str(4, v.Unavailable)
	w.Str(5, v.Query)
	w.Str(6, v.Placeholder)
	w.Struct(7, func() { v.Content.encodeWire(w) })
}

// wireAgState encodes agState as an RZW1 document (nil = over-size; caller falls back to v1).
func wireAgState(v agState) []byte {
	w := zigui.NewWireWriter(wireMsgAgState, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLogsState encodes logsState as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLogsState(v logsState) []byte {
	w := zigui.NewWireWriter(wireMsgLogsState, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLogsLines encodes logsLines as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLogsLines(v logsLines) []byte {
	w := zigui.NewWireWriter(wireMsgLogsLines, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLiveState encodes liveState as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLiveState(v liveState) []byte {
	w := zigui.NewWireWriter(wireMsgLiveState, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLiveTransport encodes liveTransportSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLiveTransport(v liveTransportSt) []byte {
	w := zigui.NewWireWriter(wireMsgLiveTransport, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLiveNP encodes liveNPSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLiveNP(v liveNPSt) []byte {
	w := zigui.NewWireWriter(wireMsgLiveNP, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLiveStatus encodes liveStatusSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLiveStatus(v liveStatusSt) []byte {
	w := zigui.NewWireWriter(wireMsgLiveStatus, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLiveDecks encodes liveDecksSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLiveDecks(v liveDecksSt) []byte {
	w := zigui.NewWireWriter(wireMsgLiveDecks, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLiveSignals encodes liveSignalsSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLiveSignals(v liveSignalsSt) []byte {
	w := zigui.NewWireWriter(wireMsgLiveSignals, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLiveCockpit encodes liveCockpitSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLiveCockpit(v liveCockpitSt) []byte {
	w := zigui.NewWireWriter(wireMsgLiveCockpit, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLiveLink encodes liveLinkSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLiveLink(v liveLinkSt) []byte {
	w := zigui.NewWireWriter(wireMsgLiveLink, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLiveGraph encodes liveGraphSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLiveGraph(v liveGraphSt) []byte {
	w := zigui.NewWireWriter(wireMsgLiveGraph, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLivePerf encodes livePerfSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLivePerf(v livePerfSt) []byte {
	w := zigui.NewWireWriter(wireMsgLivePerf, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireLiveStrip encodes liveStripSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireLiveStrip(v liveStripSt) []byte {
	w := zigui.NewWireWriter(wireMsgLiveStrip, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireMoState encodes moState as an RZW1 document (nil = over-size; caller falls back to v1).
func wireMoState(v moState) []byte {
	w := zigui.NewWireWriter(wireMsgMoState, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wirePub encodes pubSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wirePub(v pubSt) []byte {
	w := zigui.NewWireWriter(wireMsgPub, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wirePubHero encodes pubHeroSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wirePubHero(v pubHeroSt) []byte {
	w := zigui.NewWireWriter(wireMsgPubHero, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireSetState encodes setState as an RZW1 document (nil = over-size; caller falls back to v1).
func wireSetState(v setState) []byte {
	w := zigui.NewWireWriter(wireMsgSetState, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireSetContent encodes setContentSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireSetContent(v setContentSt) []byte {
	w := zigui.NewWireWriter(wireMsgSetContent, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}

// wireSetStatus encodes setStatusSt as an RZW1 document (nil = over-size; caller falls back to v1).
func wireSetStatus(v setStatusSt) []byte {
	w := zigui.NewWireWriter(wireMsgSetStatus, wireSchemaHash)
	v.encodeWire(w)
	return w.Finish()
}
