// wiregen generates the RZW1 state-wire codec from ONE schema (schema.go):
//   - Go encoder methods  → internal/webui/wire_gen.go   (package webui)
//   - Zig decoder fns     → native/zigui/src/wire_gen.zig
//
// Run: GOWORK=off go run ./internal/zigui/wiregen        (from the repo root)
// or via the //go:generate line in internal/zigui/wire.go.
//
// Both outputs embed the same schemaHash + message ids, so a stale libraveui.a can never
// mis-decode a document: the header check fails and the caller falls back to v1 (JSON).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"hash"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	root := flag.String("root", ".", "repo root")
	goOut := flag.String("go", "internal/webui/wire_gen.go", "Go encoder output (relative to -root)")
	zigOut := flag.String("zig", "native/zigui/src/wire_gen.zig", "Zig decoder output (relative to -root)")
	flag.Parse()

	if err := validate(); err != nil {
		fail(err)
	}
	if err := write(filepath.Join(*root, *goOut), emitGo()); err != nil {
		fail(err)
	}
	if err := write(filepath.Join(*root, *zigOut), []byte(emitZig())); err != nil {
		fail(err)
	}
	fmt.Printf("wiregen: %d messages, schema hash 0x%08x, retained %d/%d messages [%s]\n",
		len(schema), schemaHash(), len(retainClosure()), len(retainRoots()), retainNames())
}

// clearFieldNum mirrors zigui.WireClearField / wire.zig clear_field: the retained channel's
// reserved "reset this field" tag. No schema field may use it or anything above it.
const clearFieldNum = 1023

func fail(err error) {
	fmt.Fprintln(os.Stderr, "wiregen:", err)
	os.Exit(1)
}

func write(path string, data []byte) error {
	if old, err := os.ReadFile(path); err == nil && bytes.Equal(old, data) {
		return nil // byte-identical: leave mtime alone
	}
	return os.WriteFile(path, data, 0o644)
}

// validate rejects a schema that could produce a broken codec: duplicate/zero field numbers,
// duplicate message names or ids, dangling refs.
func validate() error {
	byName := map[string]bool{}
	ids := map[int]string{}
	for _, m := range schema {
		if byName[m.name] {
			return fmt.Errorf("duplicate message %s", m.name)
		}
		byName[m.name] = true
		if m.id != 0 {
			if prev, dup := ids[m.id]; dup {
				return fmt.Errorf("message id %d used by %s and %s", m.id, prev, m.name)
			}
			ids[m.id] = m.name
		}
		nums := map[int]bool{}
		for _, f := range m.fs {
			if f.num < 1 {
				return fmt.Errorf("%s.%s: field number must be >= 1 (0 is the body terminator)", m.name, f.goF)
			}
			if f.num >= clearFieldNum {
				// The retained channel reserves it for "reset this field to its zero value".
				return fmt.Errorf("%s.%s: field number %d is reserved (>= %d)", m.name, f.goF, f.num, clearFieldNum)
			}
			if nums[f.num] {
				return fmt.Errorf("%s: duplicate field number %d", m.name, f.num)
			}
			nums[f.num] = true
		}
	}
	for _, m := range schema {
		for _, f := range m.fs {
			switch f.kind {
			case kStruct, kList, kOptPtr, kOptVal:
				if !byName[f.ref] {
					return fmt.Errorf("%s.%s: unknown message %q", m.name, f.goF, f.ref)
				}
			}
		}
	}
	return nil
}

func roots() []msg {
	var out []msg
	for _, m := range schema {
		if m.id != 0 {
			out = append(out, m)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].id < out[j].id })
	return out
}

// ── Go emitter ──

func emitGo() []byte {
	var b strings.Builder
	p := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }
	p("// Code generated by internal/zigui/wiregen. DO NOT EDIT.")
	p("")
	p("package webui")
	p("")
	p(`import "rave.page/mate/internal/zigui"`)
	p("")
	p("// RZW1 state-wire encoders (the binary v2 path; the JSON v1 path stays for fallback).")
	p("// Field numbers + hash come from internal/zigui/wiregen/schema.go - regenerate, never edit.")
	p("const (")
	p("\twireSchemaHash uint32 = 0x%08x", schemaHash())
	for _, m := range roots() {
		p("\twireMsg%s uint16 = %d // %s", m.name, m.id, m.doc)
	}
	p(")")
	for _, m := range schema {
		p("")
		p("func (v %s) encodeWire(w *zigui.WireWriter) {", m.goT)
		if len(m.fs) == 0 {
			p("\t_ = w")
		}
		for _, f := range m.fs {
			switch f.kind {
			case kStr:
				p("\tw.Str(%d, v.%s)", f.num, f.goF)
			case kBool:
				p("\tw.Bool(%d, v.%s)", f.num, f.goF)
			case kUint:
				p("\tw.Uint(%d, uint64(v.%s))", f.num, f.goF)
			case kStruct:
				p("\tw.Struct(%d, func() { v.%s.encodeWire(w) })", f.num, f.goF)
			case kList:
				p("\tw.List(%d, len(v.%s), func(i int) { v.%s[i].encodeWire(w) })", f.num, f.goF, f.goF)
			case kStrAlways:
				p("\tw.StrAlways(%d, v.%s)", f.num, f.goF)
			case kOptPtr:
				p("\tif v.%s != nil {", f.goF)
				p("\t\tw.OptStruct(%d, func() { v.%s.encodeWire(w) })", f.num, f.goF)
				p("\t}")
			case kOptVal:
				p("\tw.OptStruct(%d, func() { v.%s.encodeWire(w) })", f.num, f.goF)
			case kStrList:
				p("\tw.StrList(%d, v.%s)", f.num, f.goF)
			}
		}
		p("}")
	}
	for _, m := range roots() {
		p("")
		p("// wire%s encodes %s as an RZW1 document (nil = over-size; caller falls back to v1).", m.name, m.goT)
		p("func wire%s(v %s) []byte {", m.name, m.goT)
		p("\tw := zigui.NewWireWriter(wireMsg%s, wireSchemaHash)", m.name)
		p("\tv.encodeWire(w)")
		p("\treturn w.Finish()")
		p("}")
	}
	emitGoRetain(p)
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fail(fmt.Errorf("gofmt: %w", err))
	}
	return src
}

// ── Zig emitter ──

func emitZig() string {
	var b strings.Builder
	p := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }
	p("//! Code generated by internal/zigui/wiregen. DO NOT EDIT.")
	p("//! RZW1 state-wire decoders (the binary v2 path). Strings are slices INTO the input")
	p("//! buffer (zero-copy); lists come from the parse arena. Unknown field numbers are")
	p("//! skipped, so a newer Go encoder stays readable; a schema-hash mismatch is rejected")
	p("//! by wire.parse before any field is read.")
	p("")
	p("const std = @import(\"std\");")
	p("const wire = @import(\"wire.zig\");")
	for _, im := range zigImports {
		p("const %s = @import(\"%s\");", im[0], im[1])
	}
	p("")
	p("pub const schema_hash: u32 = 0x%08x;", schemaHash())
	for _, m := range roots() {
		p("pub const msg_%s: u16 = %d; // %s", snake(m.name), m.id, m.doc)
	}
	for _, m := range schema {
		p("")
		p("pub fn decode%s(r: *wire.Reader, out: *%s) wire.Error!void {", m.name, m.zigT)
		if len(m.fs) == 0 {
			p("    _ = out;")
			p("    while (try r.next()) |t| try r.skip(t);")
			p("}")
			continue
		}
		p("    while (try r.next()) |t| switch (t.field) {")
		for _, f := range m.fs {
			switch f.kind {
			case kStr:
				p("        %d => out.%s = try r.str(t),", f.num, f.zigF)
			case kBool:
				p("        %d => out.%s = try r.boolean(t),", f.num, f.zigF)
			case kUint:
				p("        %d => out.%s = @intCast(try r.uint(t)),", f.num, f.zigF)
			case kStruct:
				p("        %d => out.%s = try r.sub(%s, decode%s, t),", f.num, f.zigF, refZig(f.ref), f.ref)
			case kList:
				p("        %d => out.%s = try r.list(%s, decode%s, t),", f.num, f.zigF, refZig(f.ref), f.ref)
			case kStrAlways:
				p("        %d => out.%s = try r.str(t),", f.num, f.zigF)
			case kOptPtr, kOptVal: // Zig `?T`: r.sub returns T, which coerces
				p("        %d => out.%s = try r.sub(%s, decode%s, t),", f.num, f.zigF, refZig(f.ref), f.ref)
			case kStrList:
				p("        %d => out.%s = try r.strList(t),", f.num, f.zigF)
			}
		}
		p("        else => try r.skip(t),")
		p("    };")
		p("}")
	}
	emitZigRetain(p)
	// A compile-time guard: every generated decoder is referenced, and the message ids are unique.
	p("")
	p("test \"schema ids are distinct\" {")
	for i, m := range roots() {
		for _, other := range roots()[i+1:] {
			p("    try std.testing.expect(msg_%s != msg_%s);", snake(m.name), snake(other.name))
		}
	}
	p("}")
	return b.String()
}

func refZig(name string) string {
	for _, m := range schema {
		if m.name == name {
			return m.zigT
		}
	}
	return "?"
}

// ── helpers ──

func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r + 32)
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

func itoa(i int) string { return strconv.Itoa(i) }

func fmtWrite(h hash.Hash32, parts ...string) {
	for _, p := range parts {
		_, _ = h.Write([]byte(p))
		_, _ = h.Write([]byte{0})
	}
}
